# Your workflow name.
name: Pipeline steps.

on:
  push:
    branches: [master, main]

# Your workflows jobs.
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Golangci Lint
        uses: golangci/golangci-lint-action@v2.5.2

      - name: Race condition
        run: go test -race ./domain/*

      - name: Test
        run: go test -v ./...

      - name: Deploy
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          docker_options: "--no-cache"